### PR TITLE
fixes node title not changing

### LINKED ISSUE #484: node title change breaks
When you are editing a nodes title after some time it starts breaking, it seems to happen the moment you have other graphs open.

### PR DESCRIPTION
**Pull request by mck**
Closes #484

### CODE REVIEW

File: packages/graph-editor/src/components/panels/nodeSettings/index.tsx [hunk 1]
```diff
@@ -81,34 +81,48 @@ const Annotations = observer(({ annotations }: Record<string, unknown>) => {
...
 });
 
-const NodeTitle = ({ selectedNode }: { selectedNode: Node }) => {
+const NodeTitle = observer(({ selectedNode }: { selectedNode: Node }) => {
+  const [localTitle, setLocalTitle] = React.useState(
+    (selectedNode.annotations[title] as string) || '',
+  );
+
+  // Update local state when the annotation changes
+  React.useEffect(() => {
```
Comment (SorsOps) [inline packages/graph-editor/src/components/panels/nodeSettings/index.tsx:90]: The observer should trigger the rerender anyway, we shouldn't need to update the local state

File: packages/graph-editor/src/components/panels/nodeSettings/index.tsx [hunk 2]
```diff
@@ -81,34 +81,48 @@ const Annotations = observer(({ annotations }: Record<string, unknown>) => {
   );
 });
 
-const NodeTitle = ({ selectedNode }: { selectedNode: Node }) => {
+const NodeTitle = observer(({ selectedNode }: { selectedNode: Node }) => {
```
Comment (SorsOps) [inline packages/graph-editor/src/components/panels/nodeSettings/index.tsx:84]: We should be observing the annotations, not the node

File: packages/graph-editor/src/components/panels/nodeSettings/index.tsx [hunk 3]
```diff
@@ -120,11 +134,11 @@ const NodeDescription = ({
...
         onChange={onChangeDesc}
-        value={annotations[description] as string}
+        value={localDescription}
       />
     </Stack>
   );
-};
+});
 
 const NodeSettings = ({
```
Comment (SorsOps) [inline packages/graph-editor/src/components/panels/nodeSettings/index.tsx:143]: We could actually do an observer here in the node Settings once to auto rerender the attributes here
