### PR TITLE
Fixed not being able to drag nodes at same Y position as the toolbar

### LINKED ISSUE #617: impossible to move nodes from behind toolbar
The toolbar hitbox seems to be 100% wide

Image

### PR DESCRIPTION
**Pull request by AlexBxl**
### **User description**
# Description

* Fixed not being able to drag nodes at same Y position as the toolbar

Fixes #617

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshots or video (if necessary):

a4764c1b-3704-4b8a-8546-2cb2237b412b

___

### **PR Type**
Bug fix

___

### **Description**
- Fixed issue preventing node dragging behind toolbar.

- Added `pointerEvents: none` to toolbar container style.

- Ensured toolbar retains interactive pointer events.

- Added changeset entry for the fix.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>graph.tsx</strong><dd><code>Adjust toolbar container to allow interactions behind</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

packages/graph-editor/src/editor/graph.tsx

<li>Added <code>pointerEvents: none</code> to toolbar container style.<br> <li> Ensured toolbar does not block interactions behind it.

</details>

  </td>
  <td><a href="https://github.com/tokens-studio/graph-engine/pull/636/files#diff-0a5251be74b5e25cb4df55d09e1906b29f32d52ea95168b26c72ccfdd66d2c30">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>toolbar.module.css</strong><dd><code>Maintain toolbar interactivity with pointer-events adjustment</code></dd></summary>
<hr>

packages/graph-editor/src/components/toolbar/toolbar.module.css

<li>Set <code>pointer-events: auto</code> for toolbar itself.<br> <li> Ensured toolbar remains interactive while container is transparent.

</details>

  </td>
  <td><a href="https://github.com/tokens-studio/graph-engine/pull/636/files#diff-f8248b51f7076fa9fdf681e01f174a39a71e48597373a1dd451c8dab7ef32c5f">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>proud-balloons-remember.md</strong><dd><code>Add changeset entry for toolbar drag fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.changeset/proud-balloons-remember.md

<li>Added changeset entry describing the bug fix.<br> <li> Documented fix for dragging nodes behind toolbar.

</details>

  </td>
  <td><a href="https://github.com/tokens-studio/graph-engine/pull/636/files#diff-cd671bff7474fb25c56d05b408fd3b24a40279be54da2a6ef63ddb20008cee34">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

File: packages/graph-editor/src/editor/graph.tsx [hunk 1]
```diff
@@ -821,6 +821,7 @@ export const EditorApp = React.forwardRef<
                   display: 'grid',
                   placeItems: 'center',
```
Comment (mck) [inline packages/graph-editor/src/editor/graph.tsx:822]: since we are touching this, can we move that css to the modules file?

**Review by mck — APPROVED** [review]
